var products = [
  {
    id: 1,
    ids_cart: 11,
    name: "Товар 1",
    image1: "images/sweater.jpg",
    image2: "images/sweater2.jpeg",
    image3: "images/sweater3.jpg",
    prices: { new: 40, old: 50 },
    tieser: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    article: "#37555",
    sizes: ["L", "S", "M"],
  },
  {
    id: 2,
    ids_cart: 12,
    name: "Товар 2",
    image1: "images/socks.jpg",
    image2: "images/socks2.jpg",
    image3: "images/socks3.jpg",
    prices: { new: 80, old: 90 },
    tieser:
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    article: "#34550",
    sizes: ["L", "S", "M"],
  },
  {
    id: 3,
    ids_cart: 13,
    name: "Товар 3",
    image1: "images/scarf.jpg",
    image2: "images/scarf2.jpg",
    image3: "images/scarf3.jpg",
    prices: { new: 150, old: 170 },
    tieser:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    article: "#31555",
    sizes: ["L", "S", "M"],
  },
  {
    id: 4,
    ids_cart: 14,
    name: "Товар 4",
    image1: "images/shal.webp",
    image2: "images/shal.webp",
    image3: "images/shal.webp",
    prices: { new: 100, old: 120 },
    tieser: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    article: "#34255",
    sizes: ["L", "S", "M"],
  },
  {
    id: 5,
    ids_cart: 15,
    name: "Товар 5",
    image1: "images/gloves.jpg",
    image2: "images/gloves2.jpg",
    image3: "images/gloves3.jpg",
    prices: { old: 120 },
    tieser: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    article: "#34552",
    sizes: ["L", "S", "M"],
  },
  {
    id: 6,
    ids_cart: 16,
    name: "Товар 6",
    image1: "images/sweater4.jpg",
    image2: "images/sweater5.jpg",
    image3: "images/sweater6.jpg",
    prices: { old: 90 },
    tieser:
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    article: "#34555",
    sizes: ["L", "S", "M"],
  },
  {
    id: 7,
    ids_cart: 17,
    name: "Товар 7",
    image1: "images/pled.jpg",
    image2: "images/pled2.jpg",
    image3: "images/pled.png",
    prices: { new: 150, old: 170 },
    tieser:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    article: "#34555",
    sizes: ["L", "S", "M"],
  },
  {
    id: 8,
    ids_cart: 18,
    name: "Товар 8",
    image1: "images/cap.jpg",
    image2: "images/cardigan.jpg",
    image3: "images/bag.jpg",
    prices: { new: 100, old: 120 },
    tieser: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    article: "#34554",
    sizes: ["L", "S", "M"],
  },
];
