var products = [
  {
    id: 1,
    ids_cart: 11,
    name: "Product 1",
    image1: "images/socks.jpg",
    image2: "images/scarf.jpg",
    image3: "images/scarf.jpg",
    prices: { new: 100, old: 120 },
    tieser: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    article: "#37555",
    sizes: ["L", "S", "M"],
  },
  {
    id: 2,
    ids_cart: 12,
    name: "Product 2",
    image1: "images/scarf.jpg",
    image2: "images/socks.jpg",
    image3: "images/scarf.jpg",
    prices: { new: 80, old: 90 },
    tieser:
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    article: "#34550",
    sizes: ["L", "S", "M"],
  },
  {
    id: 3,
    ids_cart: 13,
    name: "Product 3",
    image1: "images/scarf.jpg",
    image2: "images/scarf.jpg",
    image3: "images/scarf.jpg",
    prices: { new: 150, old: 170 },
    tieser:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    article: "#31555",
    sizes: ["L", "S", "M"],
  },
  {
    id: 4,
    ids_cart: 14,
    name: "Product 4",
    image1: "images/scarf.jpg",
    image2: "images/scarf.jpg",
    image3: "images/scarf.jpg",
    prices: { new: 100, old: 120 },
    tieser: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    article: "#34255",
    sizes: ["L", "S", "M"],
  },
  {
    id: 5,
    ids_cart: 15,
    name: "Product 5",
    image1: "images/scarf.jpg",
    image2: "images/scarf.jpg",
    image3: "images/scarf.jpg",
    prices: { old: 120 },
    tieser: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    article: "#34552",
    sizes: ["L", "S", "M"],
  },
  {
    id: 6,
    ids_cart: 16,
    name: "Product 6",
    image1: "images/scarf.jpg",
    image2: "images/scarf.jpg",
    image3: "images/scarf.jpg",
    prices: { old: 90 },
    tieser:
      "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    article: "#34555",
    sizes: ["L", "S", "M"],
  },
  {
    id: 7,
    ids_cart: 17,
    name: "Product 7",
    image1: "images/scarf.jpg",
    image2: "images/scarf.jpg",
    image3: "images/scarf.jpg",
    prices: { new: 150, old: 170 },
    tieser:
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    article: "#34555",
    sizes: ["L", "S", "M"],
  },
  {
    id: 8,
    ids_cart: 18,
    name: "Product 8",
    image1: "images/scarf.jpg",
    image2: "images/scarf.jpg",
    image3: "images/scarf.jpg",
    prices: { new: 100, old: 120 },
    tieser: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    article: "#34554",
    sizes: ["L", "S", "M"],
  },
];
